//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace infraccionesITM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FotoInfraccion
    {
        public int idFoto { get; set; }
        public string NombreFoto { get; set; }
        public int idInfraccion { get; set; }
    
        public virtual Infraccion Infraccion { get; set; }
    }
}
