//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace infraccionesITM.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.Infraccions = new HashSet<Infraccion>();
        }
    
        public string Placa { get; set; }
        public string TipoVehiculo { get; set; }
        public string Marca { get; set; }
        public string Color { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Infraccion> Infraccions { get; set; }
    }
}
